---

- hosts: node1
  gather_facts: true
  become: true
  tasks:
    
    - name: create data dir
      file:
        path: /data/zookeeper
        state: directory
        owner: vagrant
        group: vagrant

    - name: set zk id
      template:
        src: ./templates/zk.myid.j2
        dest: /data/zookeeper/myid
        owner: vagrant
        group: vagrant
        force: true

    - name: load zk properties
      template:
        src: ./templates/zookeeper.properties.j2
        dest: /opt/kafka/config/zookeeper.properties
        owner: vagrant
        group: vagrant
        force: true

    - name: define zk service
      template:
        src: ./templates/zookeeper.service.j2
        dest: /etc/init.d/zookeeper
        owner: root
        group: root
        mode: a+x
        force: true
    
    - name: start zk service
      command: sudo service zookeeper start