---
- name: create data dir
  file:
    path: /data/zookeeper
    state: directory
    owner: vagrant
    group: vagrant
  tags:
   - zookeeper

- name: set zk id
  template:
    src: templates/zk.myid.j2
    dest: /data/zookeeper/myid
    owner: vagrant
    group: vagrant
    force: true
  tags:
   - zookeeper

- name: load zk properties
  template:
    src: templates/zookeeper.properties.j2
    dest: /opt/kafka/config/zookeeper.properties
    owner: vagrant
    group: vagrant
    force: true
  with_items: "{{ groups['all'] }}"
  # notify:
  #  - restart zookeeper
  tags:
   - zookeeper

- name: define zk service
  copy:
    src: files/zookeeper.service
    dest: /etc/init.d/zookeeper
    owner: root
    group: root
    mode: a+x
    force: true
  notify:
   - start zookeeper
  tags:
   - zookeeper

- name: start zookeeper service
  command: service zookeeper start
  tags:
   - zookeeper