---
- name: Install a list of packages
  yum:
    name:
      - fontconfig
      - freetype*
      - urw-fonts
      - initscripts
      - wget
    state: present

- name: Add Grafana YUM Repo
  yum_repository:
    name: grafana
    description: Grafana YUM repo
    baseurl: https://packages.grafana.com/oss/rpm
    repo_gpgcheck: yes
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.grafana.com/gpg.key
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt

- name: Install Grafana
  yum:
    name:
      - grafana
    state: present

- name: Start service grafana-server, if not started
  service:
    name: grafana-server
    state: started

- name: Enable service grafana-server
  service:
    name: grafana-server
    enabled: yes

- name: Add the user prometheus
  user:
    name: prometheus
    create_home: false
    shell: /bin/false

- name: Create directories
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Cnange prom lib owner
  file:
    path: /var/lib/prometheus
    owner: prometheus
    group: prometheus

# - name: Download prometheus binaries
#   get_url:
#     url: https://github.com/prometheus/prometheus/releases/download/v2.7.1/prometheus-2.7.1.linux-amd64.tar.gz
#     dest: /tmp/prometheus.tar.gz

- name: Download & Unarchive prometheus binaries
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.7.1/prometheus-2.7.1.linux-amd64.tar.gz
    dest: /tmp
    remote_src: true

- name: Move binaries and config
  command: mv /tmp/prometheus-2.7.1.linux-amd64/console_libraries /etc/prometheus
  ignore_errors: true

- name: Move binaries and config
  command: mv /tmp/prometheus-2.7.1.linux-amd64/consoles /etc/prometheus
  ignore_errors: true
  
- name: Load Yaml config
  copy: 
    src: files/prometheus.yml
    dest: /etc/prometheus
    group: prometheus
    owner: prometheus
    mode: '0644'

- name: Set kafka and Zookeeper Prometheus Rules
  copy: 
    src: "{{ item }}"
    dest: /etc/prometheus
    group: prometheus
    owner: prometheus
    mode: '0644'
  loop:
    - files/kafka.yml
    - files/zookeeper.yml

- name: Change prom lib owner
  file:
    path: /etc/prometheus
    owner: prometheus
    group: prometheus
    recurse: true

- name: Move binaries and config
  command: mv /tmp/prometheus-2.7.1.linux-amd64/prometheus /usr/local/bin/
  ignore_errors: true

- name: Move binaries and config
  command: mv /tmp/prometheus-2.7.1.linux-amd64/promtool /usr/local/bin/
  ignore_errors: true

- name: Cnange prom lib owner
  file:
    path: /usr/local/bin/prometheus
    owner: prometheus
    group: prometheus

- name: Cnange prom lib owner
  file:
    path: /usr/local/bin/promtool
    owner: prometheus
    group: prometheus

- name: Create Prom Service file
  template:
    src: templates/prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify:
    - reload systemctl

- name: Start service prometheus, if not started
  service:
    name: prometheus
    state: started

- name: Enable service prometheus
  service:
    name: prometheus
    enabled: yes

- name: Configure Prometheus as datasource to Grafana
  uri: 
    force: True
    force_basic_auth: True
    user: "admin"
    password: "admin"
    url: "http://localhost:3000/api/datasources"
    body_format: "json"
    method: "POST"
    validate_certs: False
    body: "{{ lookup('template', 'templates/grafana_datasource_post_payload.j2') }}"
  register: grafana_api_result
  vars:
    prometheus_host: "http://localhost:9090"
  ignore_errors: true

- name: Create Kafka user in Grafana
  uri: 
    force: True
    force_basic_auth: True
    user: "admin"
    password: "admin"
    url: "http://localhost:3000/api/admin/users/"
    body_format: "json"
    method: "POST"
    validate_certs: False
    body: "{{ lookup('template', 'templates/grafana_admin_post_payload.j2') }}"
  register: grafana_api_result
  ignore_errors: true

- name: Set Kafka user as Admin in Grafana
  uri: 
    force: True
    force_basic_auth: True
    user: "admin"
    password: "admin"
    url: "http://localhost:3000/api/org/users/{{ grafana_api_result.json.id }}/"
    body_format: "json"
    method: "PATCH"
    validate_certs: False
    body: "{{ lookup('template', 'templates/grafana_admin_put_payload.j2') }}"
  register: grafana_api_result
  ignore_errors: true

- name: Upload dashboards
  uri: 
    force: True
    force_basic_auth: True
    user: "admin"
    password: "admin"
    url: "http://localhost:3000/api/dashboards/db"
    body_format: "json"
    method: "POST"
    validate_certs: False
    body: "{{ lookup('file', 'templates/{{ dashboard_payload }}') }}"
  register: grafana_api_result
  vars:
    dashboard_payload: "{{ item }}"
  with_items:
    - kafka_dashboard.json.j2
  ignore_errors: true