---
- name: create data dir
  file:
    path: /data/kafka
    state: directory
    owner: vagrant
    group: vagrant

- name: load Kafka server properties
  template:
    src: templates/server.properties.j2
    dest: /opt/kafka/config/server.properties
    owner: vagrant
    group: vagrant
    force: true

- name: define Kafka service
  template:
    src: templates/kafka.service.j2
    dest: /etc/init.d/kafka
    owner: root
    group: root
    mode: a+x
    force: true

- name: start Kafka service
  command: sudo service kafka start