---
- name: Install a list of packages
  yum:
    name:
      - nc
      - java-1.8.0-openjdk
    state: present
  tags:
    - common

- name: disable Swap
  command: swapoff -a
  tags:
    - common

- name: disable fstab
  command: sed -i '/ swap / s/^/#/' /etc/fstab
  tags:
    - common

- name: Create directories
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - /opt/kafka
  tags:
    - common

- name: Download & Unarchive Kafka binaries
  unarchive:
    src: http://mirror.cogentco.com/pub/apache/kafka/2.2.0/kafka_2.12-2.2.0.tgz
    dest: /opt/kafka/
    remote_src: true
    extra_opts: [--strip-components=1]
  tags:
    - common

- name: Download JMX Prometheus Exporter
  get_url:
    url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.12.0/jmx_prometheus_javaagent-0.12.0.jar
    dest: /opt/kafka
    mode: '0644'
    remote_src: true
  tags:
    - common

- name: Set kafka and Zookeeper Prometheus Rules
  copy: 
    src: "{{ item }}"
    dest: /opt/kafka
    mode: '0644'
  loop:
    - files/kafka.yml
    - files/zookeeper.yml
  tags:
    - common