---
- name: create data dir
  file:
    path: /data/kafka
    state: directory
    owner: vagrant
    group: vagrant
  tags:
   - kafka

- name: load Kafka server properties
  template:
    src: templates/server.properties.j2
    dest: /opt/kafka/config/server.properties
    owner: vagrant
    group: vagrant
    force: true
  # notify:
  #   - restart kafka
  tags:
   - kafka

- name: adjust heap values
  shell: |
    sed -i 's/Xms1G/Xms512M/g' /opt/kafka/bin/kafka-server-start.sh
    sed -i 's/Xmx1G/Xmx512M/g' /opt/kafka/bin/kafka-server-start.sh
  tags:
   - kafka

- name: define Kafka service
  copy:
    src: files/kafka.service
    dest: /etc/init.d/kafka
    owner: root
    group: root
    mode: a+x
    force: true
  notify:
    - start kafka
  tags:
   - kafka

- name: start kafka service
  command: service kafka start
  tags:
   - kafka