# /etc/docker/compose/kafka-manager/docker-compose.yml
version: '3.6'
services:
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "192.168.2.110:2181,192.168.2.111:2181,192.168.2.112:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null