---

- hosts: all
  gather_facts: true
  become: true
  tasks:
    - ping:

    - name: add nodes to known hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$' 
        line: "{{ hostvars[item].ansible_host }} {{item}}" 
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups['all'] }}"